#!/bin/bash
#
# $Id: dlgindex,v 1.3 2004-03-27 22:50:19 psy Exp $
#
# This shell script generates an index of DLG messages

cat > index_subject.html <<EOF
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=us-ascii" />
    <title>$TITLE: Message index</title>
  </head>
  <body>
    <h1>$TITLE: Message index</h1>

    <table>
	<tr>
	    <th><a href="index_subject.html">Subject</a></th>
	    <th><a href="index_author.html">Author</a></th>
	    <th><a href="index_date.html">Date</a></th>
	</tr>
EOF

cp index_subject.html index_author.html
cp index_subject.html index_date.html

for f in $PREFIX*
do
    echo Processing $f... 1>&2
    FROM=`head -1 $f | cut -c12-43 | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
    DATE=`head -3 $f | tail -1 | cut -c12- | sed -e 's/ 93 / 1993 /'`
    DATE=`date --date="$DATE" +'%Y-%m-%d %H:%M'`
    SUBJECT=`head -4 $f | tail -1 | cut -c12- | sed -e 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g'`
    cat >>/tmp/dlgindex.$$ <<EOF
<tr><td><a href="$f.html">$SUBJECT</a></td><td>$FROM</td><td>$DATE</td></tr>
EOF
done

sort --field-separator='>' +8 /tmp/dlgindex.$$ > /tmp/dlgindex.$$~
cat /tmp/dlgindex.$$~ >> index_date.html
sort --field-separator='>' +3 /tmp/dlgindex.$$~ >> index_subject.html
sort --field-separator='>' +6 /tmp/dlgindex.$$~ >> index_author.html

cat >/tmp/dlgindex.$$ <<EOF
    </table>
    <hr />
    <p><a style="font-size: smaller" href="index.html">Sage's Desk AD&amp;D</a></p>
  </body>
</html>
EOF

cat /tmp/dlgindex.$$ >> index_subject.html
cat /tmp/dlgindex.$$ >> index_author.html
cat /tmp/dlgindex.$$ >> index_date.html

rm /tmp/dlgindex.$$
rm /tmp/dlgindex.$$~
